### ISSUE TITLE
XMPP (RFC 6120), PubSub (XEP-0060) and Atom Over XMPP (RFC 4287)

### ISSUE THREAD

**Issue by sjehuda** [acavalin/rrss#1]
Greetings!

My name is Schimon and I am a champion of Syndication and XMPP.

For those of you who are not famiiliar, XMPP (previously Jabber) is a messaging system with open standards. XMPP is extensible via XEP.

I will discuss about XEP-0060: Publish-Subscribe.

Almost a couple of decades ago, a [discussion](https://datatracker.ietf.org/meeting/66/materials/slides-66-atompub-1.pdf) arose about incorporating Atom (RFC 4287) with XMPP PubSub, which is really easy because both are XML data.

One of the major benefits of utilizing PubSub is native Push Notifications (yes, that technique was much before HTML5) which do not require HTTP pulling.

That would be a great feature to have rrss to utilize XMPP PubSub natively!

See a [proof of concept](https://codeberg.org/poezio/slixmpp/issues/3526) I have made to parse PubSub nodes as Atom Syndication Format.

https://datatracker.ietf.org/meeting/66/materials/slides-66-atompub-1.pdf
https://codeberg.org/poezio/slixmpp/issues/3526

Cheers,
Schimon

**Comment by acavalin** [comment]
Hello, thanks for your suggestion, but I will not implement it in RRSS because I think it will not add any real value to an RSS feed aggregator/reader:

- :snail: most RSS data does not update frequently
- :book: the person reading RSS opens the app only when needed
- :1234: subscribing to a lot of different services requires to keep alive an equal amount of connections

XMPP is a protocol for near-real-time messaging and I don't think it fits well in this scenario.

**Comment by acavalin** [comment]
Hello, thanks for your suggestion, but I will not implement it in RRSS because I think it will not add any real value to an RSS feed aggregator/reader:

- :snail: most RSS data does not update frequently
- :book: the person reading RSS opens the app only when needed
- :1234: subscribing to a lot of different services requires to keep alive an equal amount of connections

XMPP is a protocol for near-real-time messaging and I don't think it fits well in this scenario.

**Comment by sjehuda** [comment]
Did you try the Python script I have linked to?

I ask, because it is important for me to have you getting an impression
from the resulted Atom XML file which that script generates.

> most RSS data does not update frequently

It is not about frequency, it is about being notified by the publishing
source instead of pulling the same data over and over again.

> subscribing to a lot of different services requires to keep alive an
> equal amount of connections

This is not accurate. The only connection to maintain is of XMPP client
account, which is only one connection to the XMPP server itself.

There is a library for Ruby at http://xmpp4r.github.io/

The author is active in XMPP for Rust groupchat and I suppose he can
help.

> XMPP is a protocol for near-real-time messaging and I don't think it
> fits well in this scenario.

It does a great job at publishing. Please try Movim and see for
yourself. https://github.com/movim/movim
